"""add length and format to summaries

Revision ID: ae6f4c33ef5c
Revises: 44e4dc020b12
Create Date: 2026-03-05 08:43:01.828909

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ae6f4c33ef5c"
down_revision: str | Sequence[str] | None = "44e4dc020b12"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "summaries",
        sa.Column("length", sa.String(), server_default="medium", nullable=False),
    )
    op.add_column(
        "summaries",
        sa.Column("format", sa.String(), server_default="prose", nullable=False),
    )
    op.alter_column(
        "summaries",
        "created_at",
        existing_type=sa.DATETIME(),
        nullable=False,
        existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "summaries",
        "created_at",
        existing_type=sa.DATETIME(),
        nullable=True,
        existing_server_default=sa.text("(CURRENT_TIMESTAMP)"),
    )
    op.drop_column("summaries", "format")
    op.drop_column("summaries", "length")
    # ### end Alembic commands ###
